version: "3"
services:
  web-services:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:80
    command: ["npm","run","debug"]
  mysql:
    image: mysql:8.0.35
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 33020:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: restaurante
      MYSQL_USER: user_restaurante
      MYSQL_PASSWORD: 54321
volumes:
  mysql_data:
    